### ISSUE TITLE
Changing the restock time on the vaults

### ISSUE THREAD

**Issue by ChargingOfficial** [EMD0123/Revault#1]
So I’m running this datapack on my server and I’ve tried everything to change the restock time down to 1-5 minutes and nothing has worked idk if I’m doing something wrong but if you could possibly assist me on this matter that would be great. (Discord is chargingofficial if that would be easiest form of communication)

**Comment by EMD0123** [comment]
The vault reset time cannot be a range, it must be a fixed value.
You can change the values by running "/function revault:gamerules" and clicking in chat which one you want to change.
values are in ticks, not seconds. Use [a tick converter](https://www.reimaginednetwork.net/minecrafttickcalculator) to convert the time you want into ticks.
